version: "3.8"

services:
  db:
    container_name: db
    image: postgres:16.1-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  rabbitmq:
    image: rabbitmq:3.12.12-management
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=${BR_USER}
      - RABBITMQ_DEFAULT_PASS=${BR_PASSWORD}
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - "5672"
      - "15672"

  app:
    env_file:
      - .env
    container_name: transaction-app
    build: ./
    command: ./transaction-app
    volumes:
      - .:/app
    ports:
      - "8080:8000"
    depends_on:
      - db
      - rabbitmq
    restart: unless-stopped

volumes:
  db-data:
